version: '3.6'
services:
  picatrix:
    image: us-docker.pkg.dev/osdfir-registry/picatrix/picatrix:latest
    env_file:
      - config.env
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    restart: on-failure
    volumes:
      - ../notebooks/:/usr/local/src/picadata/notebooks
      - /tmp/:/usr/local/src/picadata/data/
      - ../:/usr/local/src/picatrix/:ro

