name: picatrix-end-to-end
on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron:  '30 11 * * *'
jobs:
  end2end:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up infrastructure with docker-compose
        run: docker-compose -f docker/docker-build.yml up -d
        env:
          JUPYTER_PORT: 8899
      - name: Run e2e tests
        run: docker-compose -f docker/docker-build.yml exec -e PYTHONPATH="." -w /usr/local/src/picatrix -T picatrix /home/picatrix/picenv/bin/python /usr/local/src/picatrix/end_to_end_tests/tools/run_in_container.py
